# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
python:   
    - "3.5"
addons:
  apt:
    packages:
      - git
      - python-pip

before_install:    
     - pip install pytest pytest-cov   
     - pip install coveralls

install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt

script:
  - python setup.py test

after_success:
  - coveralls
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
  
cache:
  - apt
